services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - phpmyadmin
      - phpredisadmin
    environment:
      TZ: 'Europe/Moscow'
    volumes:
      - ./:/var/www
  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      TZ: 'Europe/Moscow'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      TZ: 'Europe/Moscow'
    command: --requirepass ${REDIS_PASS}
    volumes:
      - redis:/data
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: 'mysql'
      PMA_PORT: '3306'
      # PMA_USER: 'root'
      # PMA_PASSWORD: '${DB_PASS}'
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    restart: unless-stopped
    ports:
      - 8081:80
    depends_on:
      - redis
    environment:
      ADMIN_USER: 'root'
      ADMIN_PASS: '${REDIS_PASS}'
      REDIS_1_HOST: 'redis'
      REDIS_1_PORT: '6379'
      REDIS_1_AUTH: '${REDIS_PASS}'
volumes:
  mysql: null
  redis: null
