### get turl
POST http://t.tar.nz/links/shorten
Content-Type: application/json

{
  "url": "https://google.com",
  "token": "819684eb601ea10c29ee74f09d99b216",
  "expired_at": "2025-03-31 18:58",
  "custom_alias": "hellow",
  "onetime": true
}


### redirect url
GET http://t.tar.nz/hellow


### delete turl
DELETE http://t.tar.nz/links/shorten
Content-Type: application/json

{
  "turl": "http://t.tar.nz/BwWFd",
  "token": "fa1309ba55fbbdaa762e1091a56f057a"
}


### change turl
PUT http://t.tar.nz/links/shorten
Content-Type: application/json

{
  "turl": "http://t.tar.nz/BwWFd",
  "token": "fa1309ba55fbbdaa762e1091a56f057a"
}


### extend turl
PUT http://t.tar.nz/links/extend
Content-Type: application/json

{
  "turl": "http://t.tar.nz/BwWFd",
  "token": "fa1309ba55fbbdaa762e1091a56f057a",
  "expired_at": "2025-04-26 18:58:00"
}


### get stats
GET http://t.tar.nz/hellow/stats

### get turl by original_url
GET http://t.tar.nz/links/search?url=http://google.com

### get urls info by token
GET http://t.tar.nz/links/info?token=819684eb601ea10c29ee74f09d99b216
