### get turl
POST http://localhost:8000/links/shorten
Content-Type: application/json

{
  "url": "http://google.com",
  "expired_at": "2025-03-31 18:58",
  "custom_alias": "hellow",
  "onetime": true
}


### redirect url
GET http://localhost:8000/hellow


### delete turl
DELETE http://localhost:8000/links/shorten/
Content-Type: application/json

{
  "turl": "http://localhost:8000/BwWFd",
  "token": "fa1309ba55fbbdaa762e1091a56f057a"
}


### change turl
PUT http://localhost:8000/links/shorten/
Content-Type: application/json

{
  "turl": "http://localhost:8000/qM33S",
  "token": "096e0eedcd07cf5e769785f975e21291"
}


### get stats
GET http://localhost:8000/hellow/stats

### get turl from original_url
GET http://localhost:8000/links/search?original_url=http://example121.com