name: turl

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
    - name: Pytest
      run: |
        pytest
    - name: Locust
      run: |
        export PYTHONPATH=app
        locust -f tests/locustfile.py -u 50 -r 2 --headless --run-time 30s
